version = 0.1
[default.deploy.parameters]
stack_name = "nais-api-sam-stack"
resolve_s3 = true
s3_prefix = "nais-api-sam-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\" VpcId=\"vpc-08c94413911d58148\" SubnetId1=\"subnet-0c8ae2a12f53eb5de\" SubnetId2=\"subnet-02b96cea953057ac5\" ApiGatewayVpcEndpointId=\"vpce-03e2fb9671d9d8aed\" CognitoUserPoolId=\"ap-northeast-1_Di2vm2qjm\" CognitoUserPoolClientId=\"443r5ntohpimv3fao1i6p7sdkp\" AllowedEmailDomains=\"hipe.asia,gleamorb.co.jp,nais-mail.com\" AllowedEmails=\"ashley@hipe.asia,gibotajada@gmail.com,gilbert@hipe.asia,h-egoshi@gleamorb.co.jp\" WorkspaceAuthStrict=\"true\" CognitoDomainUrl=\"https://nais-stage.auth.ap-northeast-1.amazoncognito.com\" DBHost=\"nais-db.ctqbruaotie4.ap-northeast-1.rds.amazonaws.com\" DBPort=\"5432\" DBName=\"postgres\" DBUser=\"postgres\" FrontendUrl=\"https://c3cb9bzz3k.ap-northeast-1.awsapprunner.com\""
image_repositories = []
