AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Local Development Template for Nais Auth Handler'

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java11

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: com.nais.handlers.AuthHandler::handleRequest
      Environment:
        Variables:
          ENVIRONMENT: local
          LOCAL_MODE: true
          LOCAL_DEV_EMAIL: dev@example.com
          LOCAL_FRONTEND_URL: http://localhost:3000
          AUTH_LIBRARY_VERSION: 2.1.0
          AUTH_ARCHITECTURE: amplify-like
          WORKSPACE_AUTH_ENABLED: true
          STAGE: dev
      Events:
        # Health check
        HealthCheck:
          Type: Api
          Properties:
            Path: /auth/health
            Method: get
        HealthCheckOptions:
          Type: Api
          Properties:
            Path: /auth/health
            Method: options
        
        # Google OAuth login
        GoogleLogin:
          Type: Api
          Properties:
            Path: /auth/google/login
            Method: get
        GoogleLoginOptions:
          Type: Api
          Properties:
            Path: /auth/google/login
            Method: options
        
        # Google OAuth callback
        GoogleCallback:
          Type: Api
          Properties:
            Path: /auth/google/callback
            Method: get
        GoogleCallbackOptions:
          Type: Api
          Properties:
            Path: /auth/google/callback
            Method: options
        
        # Token refresh
        TokenRefresh:
          Type: Api
          Properties:
            Path: /auth/token/refresh
            Method: post
        TokenRefreshOptions:
          Type: Api
          Properties:
            Path: /auth/token/refresh
            Method: options
        
        # Logout
        Logout:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: post
        LogoutOptions:
          Type: Api
          Properties:
            Path: /auth/logout
            Method: options
        
        # Workspace domains
        WorkspaceDomains:
          Type: Api
          Properties:
            Path: /auth/workspace/domains
            Method: get
        WorkspaceDomainsOptions:
          Type: Api
          Properties:
            Path: /auth/workspace/domains
            Method: options

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for local development"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"